In [1]:
# Numpy in python
#NumPy is a Python library used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices.
#NumPy stands for Numerical Python.
import numpy as np

In [4]:
# What is data science=It is a branch of computer science  where we study how to store,
#use and anyalze data for deriving information from it

In [7]:
arr=np.array([10,2,0,3])
print(arr)
type(arr)

[10  2  0  3]


numpy.ndarray

In [8]:
import numpy as np
arr=(np.__version__)
print(arr)

1.19.5


In [8]:
data1=[[10,20.30],[40,50,60]]

In [9]:
print(data1)

[[10, 20.3], [40, 50, 60]]


In [10]:
type(data1)

list

In [11]:
arr1=np.array(data1)

<ipython-input-11-596b1e2a9ebd>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr1=np.array(data1)


In [12]:
# How create zeroes in numpy library

In [16]:
import numpy as np
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
import pandas as pd
np.arange(15).reshape(3,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
arr=np.arange(20)
print(arr[5])
print(arr[5:8])

5
[5 6 7]


In [26]:
arr=np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [28]:
print(arr[0])
print(arr[1])
print(arr[2])

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [29]:
arr[0,2]

2

In [30]:
arr2=np.array([[1,2,3],[4,6,7],[9,1,22]])
print(arr2)

[[ 1  2  3]
 [ 4  6  7]
 [ 9  1 22]]


In [32]:
print(arr2[0])
print(arr2[1])
print(arr2[2])

[1 2 3]
[4 6 7]
[ 9  1 22]


In [38]:
print(arr2[0,2])
print(arr2[1,1])
print(arr2[:2])
print(arr2[2:])
print(arr2.mean())

3
6
[[1 2 3]
 [4 6 7]]
[[ 9  1 22]]
6.111111111111111


In [40]:
import numpy as np
np.random.randint(1,50,11)


array([25, 45, 39, 27,  5, 22, 18, 26, 11, 33, 26])

In [47]:
numbers1=[10,20,30,40,50,60,70,80,90]
print(type(numbers1))
array1=np.array(numbers1)
print(type(array1))
print(np.max(array1))
print(np.min(array1))


<class 'list'>
<class 'numpy.ndarray'>
90
10


In [50]:
arr5=array1.reshape(3,3)
print(arr5)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [55]:
print(arr5.diagonal())
print(arr5.diagonal().sum())
print(arr5.argmax())
print(arr5.argmin())


[10 50 90]
150
8
0


In [63]:
prob_pred=([0.1,0.2,   0.3,0.4,  0.5,0.6,   0.9,0.1])
array2=np.array(prob_pred)
print(prob_pred)
type(array2)
len(array2)
arry8=array2.reshape(4,2)
print(arry8)

[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.9, 0.1]
[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.9 0.1]]


In [66]:
import pandas as pd
lcn=pd.read_csv(r"F:\PGA22\Data Science\pandas_Dataset\LungCapData.csv")
lcn
lcn.head()

LungCap  Age  Height Smoke  Gender Caesarean
0    6.475    6    62.1    no    male        no
1   10.125   18    74.7   yes  female        no
2    9.550   16    69.7    no  female       yes
3   11.125   14    71.0    no    male        no
4    4.800    5    56.9    no    male        no

In [69]:
print(np.unique(lcn.Smoke))
#np.sqrt(25)

['no' 'yes']


5.0

In [75]:
print(np.sqrt(25))
print(lcn.Age.mean())
print(np.percentile(lcn.Age,26))

5.0
12.326896551724138
10.0


In [79]:
print(np.power(36,0.5))
print(np.log(2.713))
print(np.abs(-7))

6.0
0.9980550336767947
7


In [81]:
# new math loibrary
import math
print(math.e)
print(math.gcd(200,25))

2.718281828459045
25


In [83]:
import numpy as np
list1=[1,11,111]
type(list1)
print(list1)
ar1=np.array(list1)
print(type(ar1))
num=np.linspace(0,10,100)
print(num)
num1=np.linspace(1,10,100)
print(num1)


[1, 11, 111]
<class 'numpy.ndarray'>
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  

In [86]:
# Randomly generate list
# in betwwen 1 to 50
import numpy as np
np.random.randint(1,50,10)
# It automatically genarte list between 10

array([32, 46, 12, 43, 42, 44, 42, 42, 20, 32])

In [90]:
numbers1 =[20 , 30 , 5 , 21,31,41, 201, 301, 201]
numbers1=np.array(numbers1)
numbers1
numbers1=numbers1.reshape(3,3)
print(numbers1)
print(numbers1.argmax())
print(numbers1.argmin())

[[ 20  30   5]
 [ 21  31  41]
 [201 301 201]]
7
2


In [99]:
# apply arithmatic operation on array
m1=np.array((11,12,13,14))
m1=m1.reshape(2,2)
print(m1)
m2=np.array((21,22,23,24))
m2=m2.reshape(2,2)
print(m2)
# Addition operation
m=m1+m2
print(m)
mk=m1-m2
print(mk)
rk=m1*m2
print(rk)

[[11 12]
 [13 14]]
[[21 22]
 [23 24]]
[[32 34]
 [36 38]]
[[-10 -10]
 [-10 -10]]
[[231 264]
 [299 336]]
